import { useMemo, useState } from 'react';
import { Link, useLocation, useParams } from 'wouter';
import { ArrowLeft, CalendarDays, Check, Ellipsis, Plus, Trash2, UserRound } from 'lucide-react';
import { useCreateTask, useDeleteTask, useGetProject, useListMembers, useListTasks, useUpdateProject, useUpdateTask, type Task, type TaskInput } from '@workspace/api-client-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { PageHeader } from '@/components/hub-shell';
import { EmptyState } from '@/pages/dashboard';

const blankTask: TaskInput = { projectId: '', title: '', description: '', status: 'todo', priority: 'medium', assigneeId: null, deadline: null, progress: 0 };
const statusNames: Record<string, string> = { backlog: 'Backlog', todo: 'To do', in_progress: 'In progress', review: 'In review', done: 'Done' };

export default function ProjectDetail() {
  const { projectId = '' } = useParams<{ projectId: string }>();
  const [, setLocation] = useLocation();
  const projectQuery = useGetProject(projectId, { query: { enabled: !!projectId, queryKey: [`/api/projects/${projectId}`] } });
  const tasksQuery = useListTasks({ projectId }, { query: { enabled: !!projectId, queryKey: ['/api/tasks', { projectId }] } });
  const membersQuery = useListMembers({ query: { queryKey: ['/api/members'] } });
  const updateProject = useUpdateProject();
  const createTask = useCreateTask();
  const updateTask = useUpdateTask();
  const deleteTask = useDeleteTask();
  const [taskDialog, setTaskDialog] = useState(false);
  const [taskForm, setTaskForm] = useState<TaskInput>({ ...blankTask, projectId });
  const [editingTask, setEditingTask] = useState<Task | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<Task | null>(null);
  const project = projectQuery.data;
  const tasks = tasksQuery.data ?? [];
  const grouped = useMemo(() => Object.entries(statusNames).map(([status, label]) => ({ status, label, tasks: tasks.filter((task) => task.status === status) })), [tasks]);
  if (projectQuery.isLoading) return <div className="animate-pulse"><div className="mb-8 h-4 w-32 rounded bg-secondary" /><div className="h-12 w-2/3 rounded bg-secondary" /><div className="mt-8 h-64 rounded-xl bg-secondary" /></div>;
  if (projectQuery.isError || !project) return <div className="py-20 text-center"><h2 className="font-bold">Project not found</h2><p className="mt-1 text-sm text-muted-foreground">This project may have been moved or deleted.</p><Button className="mt-5" onClick={() => setLocation('/projects')}>Back to projects</Button></div>;
  const updateStatus = (status: 'planning' | 'active' | 'completed' | 'archived') => updateProject.mutate({ projectId, data: { status } }, { onSuccess: () => void projectQuery.refetch() });
  const openNewTask = () => { setEditingTask(null); setTaskForm({ ...blankTask, projectId }); setTaskDialog(true); };
  const openEditTask = (task: Task) => { setEditingTask(task); setTaskForm({ projectId, title: task.title, description: task.description, status: task.status, priority: task.priority, assigneeId: task.assigneeId, deadline: task.deadline?.slice(0, 10) ?? null, progress: task.progress }); setTaskDialog(true); };
  const saveTask = (event: React.FormEvent) => { event.preventDefault(); if (!taskForm.title.trim()) return; if (editingTask) updateTask.mutate({ taskId: editingTask.id, data: taskForm }, { onSuccess: () => { setTaskDialog(false); void tasksQuery.refetch(); void projectQuery.refetch(); } }); else createTask.mutate({ data: taskForm }, { onSuccess: () => { setTaskDialog(false); void tasksQuery.refetch(); void projectQuery.refetch(); } }); };
  const removeTask = () => { if (!deleteTarget) return; deleteTask.mutate({ taskId: deleteTarget.id }, { onSuccess: () => { setDeleteTarget(null); void tasksQuery.refetch(); void projectQuery.refetch(); } }); };
  return <div className="hub-enter">
    <Link href="/projects" className="mb-6 inline-flex items-center gap-2 text-xs font-bold text-muted-foreground hover:text-foreground" data-testid="link-back-projects"><ArrowLeft size={14} />All projects</Link>
    <PageHeader eyebrow={`Project / ${project.status}`} title={project.name} description={project.description} action={<div className="flex items-center gap-2"><select value={project.status} onChange={(e) => updateStatus(e.target.value as 'planning' | 'active' | 'completed' | 'archived')} className="h-9 rounded-md border border-input bg-card px-3 text-xs font-bold" data-testid="select-project-detail-status"><option value="planning">Planning</option><option value="active">Active</option><option value="completed">Completed</option><option value="archived">Archived</option></select><Button onClick={openNewTask} className="gap-2" data-testid="button-create-task"><Plus size={16} />Add task</Button></div>} />
    <div className="mb-7 grid gap-3 sm:grid-cols-3"><div className="hub-card rounded-xl p-4"><div className="hub-label text-muted-foreground">Progress</div><div className="mt-2 flex items-end gap-2"><span className="text-2xl font-extrabold">{project.progress}%</span><span className="mb-1 text-xs text-muted-foreground">complete</span></div><div className="mt-3 h-1.5 rounded-full bg-secondary"><div className="h-full rounded-full bg-chart-2 transition-all" style={{ width: `${project.progress}%` }} /></div></div><div className="hub-card rounded-xl p-4"><div className="hub-label text-muted-foreground">Task health</div><div className="mt-2 text-2xl font-extrabold">{project.completedTaskCount}<span className="text-base font-medium text-muted-foreground"> / {project.taskCount}</span></div><div className="mt-1 text-xs text-muted-foreground">tasks completed</div></div><div className="hub-card rounded-xl p-4"><div className="hub-label text-muted-foreground">Deadline</div><div className="mt-2 flex items-center gap-2 text-lg font-extrabold"><CalendarDays size={17} className="text-accent-foreground" />{project.dueDate ? new Date(project.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : 'Not set'}</div><div className="mt-1 text-xs text-muted-foreground">Started {new Date(project.startDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</div></div></div>
    {tasks.length === 0 ? <EmptyState title="No tasks in this project" text="Break the work into a few clear next steps." action={<Button onClick={openNewTask} size="sm" data-testid="button-empty-create-task"><Plus size={14} />Add first task</Button>} /> : <div className="grid gap-4 xl:grid-cols-5">{grouped.map((column) => <section key={column.status} className="min-w-0"><div className="mb-3 flex items-center justify-between px-1"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${column.status === 'done' ? 'bg-chart-2' : column.status === 'in_progress' ? 'bg-accent' : column.status === 'review' ? 'bg-chart-4' : 'bg-muted-foreground/40'}`} /><h2 className="text-xs font-bold">{column.label}</h2></div><span className="hub-mono text-[10px] text-muted-foreground">{column.tasks.length}</span></div><div className="space-y-2">{column.tasks.map((task) => <TaskCard key={task.id} task={task} onEdit={() => openEditTask(task)} onDelete={() => setDeleteTarget(task)} onStatus={(status) => updateTask.mutate({ taskId: task.id, data: { status } }, { onSuccess: () => { void tasksQuery.refetch(); void projectQuery.refetch(); } })} />)}</div></section>)}</div>}
    <TaskDialog open={taskDialog} onOpenChange={setTaskDialog} form={taskForm} setForm={setTaskForm} editing={editingTask} members={membersQuery.data ?? []} pending={createTask.isPending || updateTask.isPending} onSubmit={saveTask} />
    <Dialog open={!!deleteTarget} onOpenChange={(open) => !open && setDeleteTarget(null)}><DialogContent className="max-w-sm"><DialogHeader><DialogTitle>Delete task?</DialogTitle><DialogDescription>“{deleteTarget?.title}” will be removed from this project.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleteTarget(null)}>Cancel</Button><Button variant="destructive" onClick={removeTask} disabled={deleteTask.isPending} data-testid="button-confirm-delete-task">Delete task</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function TaskCard({ task, onEdit, onDelete, onStatus }: { task: Task; onEdit: () => void; onDelete: () => void; onStatus: (status: 'backlog' | 'todo' | 'in_progress' | 'review' | 'done') => void }) {
  return <div className="hub-card group rounded-lg p-3.5 transition-transform hover:-translate-y-0.5" data-testid={`card-task-${task.id}`}><div className="mb-3 flex items-start justify-between gap-2"><button onClick={() => onStatus(task.status === 'done' ? 'todo' : 'done')} className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full border ${task.status === 'done' ? 'border-chart-2 bg-chart-2 text-card' : 'border-muted-foreground/45 hover:border-primary'}`} aria-label={task.status === 'done' ? 'Reopen task' : 'Complete task'} data-testid={`button-toggle-task-${task.id}`}>{task.status === 'done' && <Check size={10} strokeWidth={3} />}</button><div className="flex opacity-0 transition-opacity group-hover:opacity-100"><button onClick={onEdit} className="p-1 text-muted-foreground hover:text-foreground" aria-label="Edit task" data-testid={`button-edit-task-${task.id}`}><Ellipsis size={14} /></button><button onClick={onDelete} className="p-1 text-muted-foreground hover:text-destructive" aria-label="Delete task" data-testid={`button-delete-task-${task.id}`}><Trash2 size={13} /></button></div></div><button onClick={onEdit} className="block text-left text-sm font-bold leading-snug hover:underline" data-testid={`button-open-task-${task.id}`}>{task.title}</button><div className="mt-3 flex items-center justify-between gap-2"><span className={`rounded px-1.5 py-1 hub-label ${task.priority === 'high' ? 'bg-destructive/10 text-destructive' : task.priority === 'medium' ? 'bg-accent/20 text-foreground' : 'bg-secondary text-muted-foreground'}`}>{task.priority}</span>{task.deadline && <span className="flex items-center gap-1 hub-mono text-[9px] text-muted-foreground"><CalendarDays size={11} />{new Date(task.deadline).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span>}</div>{task.assignee && <div className="mt-3 flex items-center gap-1.5 text-[10px] text-muted-foreground"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-secondary text-[8px] font-bold"><UserRound size={10} /></span>{task.assignee.name}</div>}</div>;
}

function TaskDialog({ open, onOpenChange, form, setForm, editing, members, pending, onSubmit }: { open: boolean; onOpenChange: (open: boolean) => void; form: TaskInput; setForm: (form: TaskInput) => void; editing: Task | null; members: { id: string; name: string }[]; pending: boolean; onSubmit: (event: React.FormEvent) => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{editing ? 'Edit task' : 'Add a task'}</DialogTitle><DialogDescription>Make the next action clear and assign ownership.</DialogDescription></DialogHeader><form onSubmit={onSubmit} className="space-y-4"><label className="block text-xs font-bold">Task title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="What needs to happen?" className="mt-1.5 flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus:ring-1 focus:ring-ring" data-testid="input-task-title" /></label><label className="block text-xs font-bold">Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-1.5 min-h-20 w-full resize-none rounded-md border border-input bg-background px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-ring" data-testid="input-task-description" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-bold">Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as TaskInput['status'] })} className="mt-1.5 h-10 w-full rounded-md border border-input bg-background px-2 text-sm" data-testid="select-task-status">{Object.entries(statusNames).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-xs font-bold">Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value as TaskInput['priority'] })} className="mt-1.5 h-10 w-full rounded-md border border-input bg-background px-2 text-sm" data-testid="select-task-priority"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-bold">Assignee<select value={form.assigneeId ?? ''} onChange={(e) => setForm({ ...form, assigneeId: e.target.value || null })} className="mt-1.5 h-10 w-full rounded-md border border-input bg-background px-2 text-sm" data-testid="select-task-assignee"><option value="">Unassigned</option>{members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label className="block text-xs font-bold">Deadline<input type="date" value={form.deadline ?? ''} onChange={(e) => setForm({ ...form, deadline: e.target.value || null })} className="mt-1.5 h-10 w-full rounded-md border border-input bg-background px-2 text-sm" data-testid="input-task-deadline" /></label></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button type="submit" disabled={pending || !form.title.trim()} data-testid="button-save-task">{pending ? 'Saving…' : editing ? 'Save changes' : 'Add task'}</Button></DialogFooter></form></DialogContent></Dialog>;
}